name: mpc311-torch
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - numpy
  - matplotlib
  - tqdm
  - scipy
  - cvxpy
  - ecos
  - osqp
  - scs

